### ISSUE TITLE
Bug on same item that is swap.

### ISSUE THREAD

**Issue by zuil7** [mmick66/KDDragAndDropCollectionView#19]
Hi,

I used your library. Great library by the way. I found a bug. For example i have array of [A,B, C, D, A] when i swap A to A, the whole cell moves. Is there any solution for this? i just wanted to swap A to A. i am working on a word puzzle.

Thanks!

**Comment by mmick66** [comment]
Thank you for bringing the issue up. What do you mean swap A to A? Are they the _same_ cell? If so, how could they be swapped?

**Comment by zuil7** [comment]
Hi, no they are different cell. For example i have array of  [A,B, C, D, A]  and every cell in my collectionview has label with my array on it. So i have 5 cells now with a Letter on it. So if i swap CellB and CellC, it is ok. But when i swap Cell A to Cell A or should is say swap index 0 to index 4 the issue occurs. I hope i explain it well :)

**Comment by mmick66** [comment]
Ok I understand. When you say "the whole cell moves" what do you mean? Could you **zip** your project and drop it here? I promise to have a look...

**Comment by zuil7** [comment]
Hi,

I have attached the sample file. Try moving cell especially the last cell containing A. The animation gets scramble when try to swap it. Thanks

[KDDragAndDropCollectionView-358ff4cf5dd7a94ab594c2b6dd96b5e9896f4619 2.zip](https://github.com/mmick66/KDDragAndDropCollectionView/files/1500370/KDDragAndDropCollectionView-358ff4cf5dd7a94ab594c2b6dd96b5e9896f4619.2.zip)

**Comment by mmick66** [comment]
Great! Thanks for this... the problem is in the comparison...

```
func ==(lhs: DataItem, rhs: DataItem) -> Bool {
    return lhs.indexes == rhs.indexes && lhs.colour == rhs.colour
}
```

The idea is that you should use some custom data type that implements Equatable and write some code do distinguish one item form the other. What appears on the label does **not** have to be what the equality is based on. Have a look at your project reattached.

[KDDragAndDropCollectionView-358ff4cf5dd7a94ab594c2b6dd96b5e9896f4619.zip](https://github.com/mmick66/KDDragAndDropCollectionView/files/1502107/KDDragAndDropCollectionView-358ff4cf5dd7a94ab594c2b6dd96b5e9896f4619.zip)

**Comment by zuil7** [comment]
Thanks it worked. cheers!
