### ISSUE TITLE
Condition failed

### ISSUE THREAD

**Issue by thedahiyaboy** [mmick66/KDDragAndDropCollectionView#20]
I have UILabel in the collectionViewCell and each label have one character. Now user can move these labels and form a word or user drop these labels to another collectionview. Framework work behaving weird if there is same characters in the single word eg.  `offence` whenever I tried to move `f` and `e` the another same char also moves along it.

**Comment by mmick66** [comment]
This is probably because your cells are not **uniquely identifiable**. In other words, the only data that they have seems to be the letter in question, and since there can be cells with the same letter the equality check does not work correctly. 

Please add a property to your data item, a simple identifier will do, that will be unique for each cell and the code will work.
