### ISSUE TITLE
Is there a method to reload all collection views?

### ISSUE THREAD

**Issue by twof** [mmick66/KDDragAndDropCollectionView#25]
Looking for a way to reload all the collectionviews, retriggering all the datasource delegate methods.

Thanks!

**Comment by mmick66** [comment]
Loop over the collection views you want and call [reloadData()](https://developer.apple.com/documentation/uikit/uicollectionview/1618078-reloaddata) ?

**Comment by twof** [comment]
That would be a good convenience method to have. Might be submitting a PR for it later.

**Comment by mmick66** [comment]
What do you mean? The method above already exists. Are you saying that it would be good to have a single method to reload **all** collection views?

**Comment by twof** [comment]
Yeah that's the idea. For my use case, I'm getting data from a server and using that data to populate a bunch of your collection views. Since the data on the server is likely to change, it makes sense to be able to reload all of the collection views at once. 

If you think that's out of the scope of your library though, I won't open a PR

**Comment by mmick66** [comment]
Well, I do think it's out of scope. The thing is that one rarely needs a blanket refresh. Its always better to select which views one is updating. Besides, the collection views are updated as the drag and drop behaviour is happening so that a blanket update might interfere with the behaviour. 

I appreciate the comments though... 

PS. You know what I would also appreciate? A star ;-)

**Comment by twof** [comment]
> PS. You know what I would also appreciate? A star ;-)

Way ahead of you on that one :)
