### ISSUE TITLE
Remove Item

### ISSUE THREAD

**Issue by paulpasha** [mmick66/KDDragAndDropCollectionView#7]
Hello Michael, It would be great if you could help me with adding new function in your project. I need to place a UIButton inside the CollectionViewCell, that will remove self Cell with existing animation; same like when dragging and dropping items.

Now I realized that just by placing function in UITableViewController class and UIButton with "addTarget", but It hasn't your animation.

**Comment by mmick66** [comment]
If I understand you correctly what you are asking has little (if anything) to do with my project. However, and because I am such a great guy, I created a little project for you that hopefully has the functionality you are looking for.

[RemoveMe.zip](https://github.com/mmick66/KDDragAndDropCollectionView/files/147870/RemoveMe.zip)

**Comment by paulpasha** [comment]
Thanks a lot, great guy :) I did almost the same, but forgot about function .deleteItemsAtIndexPaths() and I found the shortest way how to reproduce a cell, I did "let cell = sender.superview!.superview as! CellClass".

**Comment by mmick66** [comment]
Yes, you can do as many superview.superview as you want but you might not know in advance how deeply you button is nested on the stack. So a general function should use the while loop as in the code. Enjoy!
